name = "garna-io"
main = "src/index.ts"
account_id = "f67149c49bb3df8b37eb59f539a72c97"
compatibility_date = "2024-12-01"

[dev]
port = 8788

[vars]
USE_STATIC_ASSETS = "true"

[assets]
directory = "./public"
binding = "ASSETS"
